### ISSUE TITLE
Blocked IPs still able to access sub pages

### ISSUE THREAD

**Issue by howdytom** [flydev-fr/Blackhole#6]
I have noticed that version Blackhole 1.1.0 does not block the entire site as stated. Once the IP address has been blocked, it is still possible to load any sub pages. It only blocks access to the front and blockhole page. Tested on PW 3.0.229 clean install. 

Thank you so much for this wonderful module.

**Comment by flydev-fr** [comment]
Hi @howdytom, 

Sorry, the main issue is that some details are missing from the readme. I think your issue is due to the output strategy used on your setup.

I mean, if you are using `delayed output` it should works as is by just calling blackhole from the home template. But if you are on `markup region` or `direct output` then you have to call the module from each template, or use a `hook`.

Which output strategy are you using on your side?

**Comment by howdytom** [comment]
Thanks for your reply.  Oh sorry, I got it now. As output strategy I am using ProcessWires default `markup region` $config->useMarkupRegions = true;. I followed the instructions without thinking. 🤦‍♂️

To call the module on all templates I have added it to the  _init.php. Now it is working as expected.
